import { Email } from 'src/entities/email.entity';
import User from 'src/entities/user.entity';
import { MigrationInterface, QueryRunner } from 'typeorm';

export class insertUsersData1685456236967 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `INSERT INTO users ("firstName", "lastName", "email", "password") VALUES
       ('John', 'Doe','john@example.com','$2b$10$rsd7fRY9WUvtrXHk5sc7HehtsMOedzGgqfXe5SEMqsopAsJSGkWTm'),
       ('Jane', 'Doe','jane@example.com','$2b$10$rsd7fRY9WUvtrXHk5sc7HehtsMOedzGgqfXe5SEMqsopAsJSGkWTm'),
       ('Ricky', 'Mickel','mickel@example.com','$2b$10$rsd7fRY9WUvtrXHk5sc7HehtsMOedzGgqfXe5SEMqsopAsJSGkWTm')`,
    );

    await queryRunner.query(
      `INSERT INTO emails ("subject", "body", "senderId", "receiverId","read") VALUES
        ('Subject', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        (SELECT id FROM users WHERE "firstName" = 'John' LIMIT 1), (SELECT id FROM users WHERE "firstName" = 'Jane' LIMIT 1),false),
        ('Subject', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        (SELECT id FROM users WHERE "firstName" = 'John' LIMIT 1), (SELECT id FROM users WHERE "firstName" = 'Jane' LIMIT 1),false),
        ('Subject', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        (SELECT id FROM users WHERE "firstName" = 'Ricky' LIMIT 1), (SELECT id FROM users WHERE "firstName" = 'Jane' LIMIT 1),false),
        ('Subject', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        (SELECT id FROM users WHERE "firstName" = 'Jane' LIMIT 1), (SELECT id FROM users WHERE "firstName" = 'John' LIMIT 1),false),
        ('Subject', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        (SELECT id FROM users WHERE "firstName" = 'Jane' LIMIT 1), (SELECT id FROM users WHERE "firstName" = 'Ricky' LIMIT 1),false),
        ('Subject', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        (SELECT id FROM users WHERE "firstName" = 'Jane' LIMIT 1), (SELECT id FROM users WHERE "firstName" = 'John' LIMIT 1),false),
        ('Dummy Subject', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        (SELECT id FROM users WHERE "firstName" = 'Ricky' LIMIT 1), (SELECT id FROM users WHERE "firstName" = 'John' LIMIT 1),false),
        ('Lorem Subject', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        (SELECT id FROM users WHERE "firstName" = 'Ricky' LIMIT 1), (SELECT id FROM users WHERE "firstName" = 'John' LIMIT 1),false),
        ('Lorem Subject', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        (SELECT id FROM users WHERE "firstName" = 'Ricky' LIMIT 1), (SELECT id FROM users WHERE "firstName" = 'Ricky' LIMIT 1),false),
        ('Lorem Subject', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        (SELECT id FROM users WHERE "firstName" = 'John' LIMIT 1), (SELECT id FROM users WHERE "firstName" = 'Ricky' LIMIT 1),false),
        ('Lorem Subject', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        (SELECT id FROM users WHERE "firstName" = 'Ricky' LIMIT 1), (SELECT id FROM users WHERE "firstName" = 'John' LIMIT 1),false),
        ('Lorem Subject', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        (SELECT id FROM users WHERE "firstName" = 'Ricky' LIMIT 1), (SELECT id FROM users WHERE "firstName" = 'John' LIMIT 1),false)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
